version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    restart: always
    expose:
      - "8000"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    env_file:
      - .env
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./dist:/app/dist
    depends_on:
      - django
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
